// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhs_LMJtiU5l9XkejEL48BFs9J_LlRvK4',
    appId: '1:261788132999:web:ab92a5030896bacf54ba22',
    messagingSenderId: '261788132999',
    projectId: 'shopapp-16095',
    authDomain: 'shopapp-16095.firebaseapp.com',
    storageBucket: 'shopapp-16095.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXxuhM-wDwxUcqP52nT2T4eqwlR-buxkM',
    appId: '1:261788132999:android:897d50b68ec2e67054ba22',
    messagingSenderId: '261788132999',
    projectId: 'shopapp-16095',
    storageBucket: 'shopapp-16095.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHYrV0N39YWxNoD_569e5YST4O4xmZ09Q',
    appId: '1:261788132999:ios:9be4bd7004a0d4c754ba22',
    messagingSenderId: '261788132999',
    projectId: 'shopapp-16095',
    storageBucket: 'shopapp-16095.firebasestorage.app',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHYrV0N39YWxNoD_569e5YST4O4xmZ09Q',
    appId: '1:261788132999:ios:9be4bd7004a0d4c754ba22',
    messagingSenderId: '261788132999',
    projectId: 'shopapp-16095',
    storageBucket: 'shopapp-16095.firebasestorage.app',
    iosBundleId: 'com.example.shopApp',
  );
}
